name: example
description: Example app for offtheline package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  offtheline:
    path: ../
  flutter_state_notifier:
  hive:
  hive_flutter:
  isar: ^2.5.0
  http:
  package_info:
  path_provider:
  provider:
  uri:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  isar_generator:

flutter:
  uses-material-design: true