name: appcore
description: Offline App Core written in pure Dart.
version: 0.11.0
homepage: https://kudosoft.net

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.0
  http: ^0.13.0
  logger: 
  state_notifier:
  uri:
