name: offtheline
description: Add offline capability to your Dart/Flutter client app.
version: 0.12.0
homepage: https://github.com/shroff/offtheline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.0
  http: ^0.13.0
  logger: 
  state_notifier:
  uri:
